"""add_response_feedback

Revision ID: c0220f51fa15
Revises: fb0a8f6262c9
Create Date: 2026-02-10 20:39:37.755482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0220f51fa15'
down_revision: Union[str, None] = 'fb0a8f6262c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_responses', sa.Column('feedback_score', sa.Integer(), nullable=True, comment='1 = Good Response, -1 = Bad Response, 0 = Neutral'))
    op.add_column('pending_responses', sa.Column('feedback_notes', sa.Text(), nullable=True, comment='User comments on the response quality'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_responses', 'feedback_notes')
    op.drop_column('pending_responses', 'feedback_score')
    # ### end Alembic commands ###
