"""Add feedback fields

Revision ID: 23cd636ddee3
Revises: 002_add_message_timestamp
Create Date: 2026-02-10 12:15:04.535873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cd636ddee3'
down_revision: Union[str, None] = '002_add_message_timestamp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('feedback_score', sa.Integer(), nullable=True, comment='1 = Like (Correct), -1 = Dislike (Incorrect), 0 = Neutral'))
    op.add_column('opportunities', sa.Column('feedback_notes', sa.Text(), nullable=True, comment='User comments explaining the feedback'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'feedback_notes')
    op.drop_column('opportunities', 'feedback_score')
    # ### end Alembic commands ###
